version: '3.8'
services:
  jaeger:
    image: jaegertracing/all-in-one   
    environment:
        - COLLECTOR_ZIPKIN_HTTP_PORT=9411
        - LOG_LEVEL=debug
    restart: on-failure
    
   
  app1:  
    build: app1/Dockerfile
    depends_on: 
      - jaeger
      - app2

  app2:  
    build: app2/Dockerfile
    depends_on: 
      - jaeger
  
  nginx:
    build: nginx_service/Dockerfile
    ports:
      - 8000:8000
    depends_on: 
      - jaeger
      - app2
      - app1
   
